### ISSUE TITLE
Error while rebooting PC

### ISSUE THREAD

**Issue by MajorXAML** [fredemmott/StreamDeck-AudioSwitcher#116]
**Describe the bug**
Since the beginning of this month, every time I restart my PC, an error window pops up for a split second. As it turned out it was an error with sdaudioswitch.exe

**To Reproduce**
1. Go to 'Windows'
2. Click on 'Start > Reboot'

**Expected behavior**
There shouldn't be any errors

**Debugging Information**
![photo_2024-03-01_11-31-51](https://github.com/fredemmott/StreamDeck-AudioSwitcher/assets/93913816/251ae5a0-c90c-448f-a4d6-31e99c7fa219)

**Log File**
I was able to find the log files only in the first path and they were simply called StreamDeck1-9 i.e no files with name com.fredemmott.discord.... I attached the latest one

https://gist.github.com/MajorXAML/9df3e4b7d9b14ff68616a0f0b6fd8b12

** Operating System **
Windows 11 Professional, 64-bit 23H2 (OS Build 22631.3155)

**Additional context**
note: the plugin was installed via Elgato Marketplace

**Comment by MajorXAML** [comment]
I mean, it works fine, but if I restart the PC, an error occurs. But if I close the StreamDeck there will be no error. anyway ty.

**Comment by fredemmott** [comment]
If this is while the PC is shutting down for reboot rather than while it's turning back on, you might want to report this to Elgato support: the streamdeck software should not attempt to relaunch plugins while windows is shutting down. One way they could handle this would be by handling WM_ENDSESSION.

The plugin has no control over whether or not this happens.
