### ISSUE TITLE
Feature Request: Toggle both input and output with same button

### ISSUE THREAD

**Issue by altano** [fredemmott/StreamDeck-AudioSwitcher#3]
Right now I have two buttons that toggle between my headset and speakers for output, and my headset and webcam for mic. I would love for that to be one button to toggle my headset for both input/output, and my speakers and webcam for mic.

**Comment by fredemmott** [comment]
Sorry, I don't think I'm going to do this: it will make the code a lot more complicated, and it's not obvious what it should show - or what pressing it should do - if for example you're using your headset for output and webcam for input, configured via some other mechanism.

Multi actions with the 'set' instead of 'toggle' would be a way to do this without changing the plugin with clearer behavior.
